on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test cases
        id: hello
        uses: ./